@hostname = localhost
@port = 3005
@host = {{hostname}}:{{port}}

###
GET http://{{host}} HTTP/1.1


### create user
POST http://{{host}}/api/v1/users HTTP/1.1
content-type: application/json

{
    "userName": "john.doe",
    "password": "secret",
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@domain.com"
}


### create product
POST http://{{host}}/api/v1/products HTTP/1.1
content-type: application/json

{
    "name": "Product 1",
    "price": 9.99
}
